# 服务器配置
[server]
host = "0.0.0.0"
port = 8080

# 数据库配置
[database]
driver = "mysql"
username = "root"
password = "Dhrsny678bjsfb@!"
host = "127.0.0.1"
port = 3306
name = "TrainTicket"
max_connections = 100

# 缓存配置
[cache]
type = "redis"
host = "127.0.0.1"
port = 6379
password = "123456"
max_idle_connections = 100
max_active_connections = 500

# 日志配置
[log]
level = "info"
path = "/root/TicketTrain/toB-train-rpc/log/train.log"

# Elasticsearch 配置
[elasticsearch]
address = "127.0.0.1:9200"
timeout = 5
max_idle_connections = 10
max_active_connections = 100
connection_request_timeout = 2